"""
    geonames/pipelines
    ~~~~~~~~~~~~~~~~~~

    Contains pipeline graph definition for ingesting source files into sqlite.
"""
from . import base, sinks, sources


Graph = base.PipelineGraph(
    pipelines=[
        base.Pipeline(
            source=sources.CountryInfo,
            sinks=[
                sinks.Currency,
                sinks.CountryCode
            ]
        ),
        base.Pipeline(
            source=sources.TimeZone,
            sinks=[
                sinks.TimeZone
            ]
        ),
        base.Pipeline(
            source=sources.FeatureClass,
            sinks=[
                sinks.FeatureClass
            ]
        ),
        base.Pipeline(
            source=sources.FeatureCode,
            sinks=[
                sinks.FeatureCode
            ]
        ),
        base.Pipeline(
            source=sources.ISOLanguage,
            sinks=[
                sinks.LanguageCode
            ]
        ),
        base.Pipeline(
            source=sources.GeonameNoCountry,
            sinks=[
                sinks.Location,
                sinks.Geoname,
                sinks.AdminCode
            ]
        ),
        base.Pipeline(
            source=sources.GeonameAllCountries,
            sinks=[
                sinks.Location,
                sinks.Geoname,
                sinks.AlternateCountryCode,
                sinks.AdminCode
            ]
        ),
        base.Pipeline(
            source=sources.Hierarchy,
            sinks=[
                sinks.Hierarchy
            ]
        ),
        base.Pipeline(
            source=sources.Continent,
            sinks=[
                sinks.Continent
            ]
        ),
        base.Pipeline(
            source=sources.Shape,
            sinks=[
                sinks.Boundary
            ]
        ),
        base.Pipeline(
            source=sources.UserTag,
            sinks=[
                sinks.UserTag
            ]
        ),
        base.Pipeline(
            source=sources.CountryInfo,
            sinks=[
                sinks.Country,
                sinks.CountryLanguage
            ]
        ),
        base.Pipeline(
            source=sources.CountryInfo,
            sinks=[
                sinks.CountryNeighbor
            ]
        ),
        base.Pipeline(
            source=sources.AlternateName,
            sinks=[
                sinks.Abbreviation,
                sinks.AirportCode,
                sinks.AlternateName,
                sinks.PostalCode,
                sinks.UserLink,
                sinks.Wikidata
            ]
        )
    ]
)
